[package]
name = "dpdp_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.97", features = ["backtrace"] }
chrono = { version = "0.4.40", features = ["serde"] }
csv = "1.3.1"
serde = { version = "1.0.219", features = ["serde_derive"] }
serde_json = "1.0.140"
